name: swift-create-xcframework

on:
  push:
    branches:
      - develop

jobs:
  create-xcframework:
    runs-on: macos-latest
    steps:
      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.CERTIFICATE_P12 }}
          p12-password: ${{ secrets.CERTIFICATE_P12_PASSWORD }}
      - name: Checkout Project
        uses: actions/checkout@v4.1.4
      - name: Build XCFramework
        run: ./buildxcf.sh
      - name: Sign
        run: |
          codesign -s "iPhone Distribution: Blazej SLEBODA (43VBDTY4E3)" \
          --force \
          --deep \
          -- $OUTPUT_DIR/$XCFRAMEWORK_NAME.xcframework
      - uses: actions/upload-artifact@v4
        with:
          name: Upload UIViewKit.xcframework to Release Assets
          path: .xcframework/UIViewKit.xcframework
