name: swift-create-xcframework

on:
  push:
    branches:
      - develop

jobs:
  create-xcframework:
    runs-on: macos-latest
    steps:
      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.CERTIFICATE_P12 }}
          p12-password: ${{ secrets.CERTIFICATE_P12_PASSWORD }}
      - name: Checkout Project
        uses: actions/checkout@v4.1.4
      - name: Build XCFramework
        run: ./buildxcf.sh
        env:
          XCFRAMEWORK_SIGN_KEY: ${{secrets.XCFRAMEWORK_SIGN_KEY}}
