name: swift-create-xcframework

on:
  push:
    branches:
      - develop

jobs:
  create-xcframework:
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: swift-create-xcframework
        uses: segment-integrations/swift-create-xcframework@2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.XCFRAMEWORK_SIGN_KEY }}
