name: swift-create-xcframework

on:
  push:
    branches:
      - develop

jobs:
  create-xcframework:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: swift-create-xcframework
        uses: segment-integrations/swift-create-xcframework@v2.4
        env:
          GITHUB_TOKEN: ${{ secrets.XCFRAMEWORK_SIGN_KEY }}
