name: SwiftLint

on: [pull_request]

jobs:
  swiftlint:
    runs-on: macos-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v2

    - name: Install SwiftLint
      run: brew install swiftlint

    - name: Run SwiftLint
      run: swiftlint

